spring:
  application:
    name: simis-erp

  datasource:
    url: jdbc:postgresql://localhost:5432/simis_collection
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true